### PR TITLE
add pre- and post-link text insertion with tests

### PR DESCRIPTION
**Pull request by andrewjhunt**
Hi,

I needed to add 🔗  link character to external links or the link SVG https://commons.wikimedia.org/wiki/File:External_link_font_awesome.svg 

The extension should be backwards compatible with your release. It adds 5 parameters for adding text (a) before / after and (b) inside / outside the <a> tag (c) on external or all links.

Up to you if you want to add it to your already-useful package.

-Andrew

### CODE REVIEW

**Comment by samiahmedsiddiqui** [comment]
@andrewjhunt Can you please change the parameters?

- textExtOnly -> externalOnly
- preOutside -> beforeLink
- preInside -> beforeLinkText
- postInside -> afterLinkText
- postOutside -> afterLink

**Comment by andrewjhunt** [comment]
Hi, parameter names changed as requested.

**Comment by samiahmedsiddiqui** [comment]
> Hi, parameter names changed as requested.

Hi @andrewjhunt Thank you for the changes. I just noticed that you have directly made the changes in the `index.js` file which is a compiled file. In actual, changes needs to be done in `index.ts` file under `src` folder and then run `npm run build` to generate the `index.js` file.

**Review by samiahmedsiddiqui — CHANGES_REQUESTED** [review]
`index.js` is a compiled file from `index.ts`. Please do all your changes to the `index.ts` file under `src` folder and then run `npm run build` command to generate the `index.js` file.

**Comment by andrewjhunt** [comment]
The param changes are applied to TS. Build working and tests passing.
Lots of TS errors from the remarkable package but perhaps that's expected?
BTW, first time using TS for me. Made best effort to get the details right.

**Comment by samiahmedsiddiqui** [comment]
@andrewjhunt Thank you for doing all of these changes, It looks good to me. Great job 👍

**Review by samiahmedsiddiqui — APPROVED** [review]
LGTM

**Pull request merged**
